### ISSUE TITLE
PC端末と携帯端末で画面の動きが違う

### ISSUE THREAD

**Issue by TomoyoshiNakata** [kitalab/Tasks#38]
PC端末ではヘッダーはスクロールされないが、携帯端末（Chromeエミュレートモード）ではヘッダーもスクロールされる。
追記:通常は携帯端末でもヘッダーはスクロールされない模様。どうやら文字が横に飛び出している（「！」を大量に入力したときなど）とヘッダーがスクロールされる？

**Comment by kitatsuw** [comment]
使用なので問題ないです。
