### ISSUE TITLE
（正常？）ブラウザの「戻る」ボタンを押下したとき、更新が反映されない

### ISSUE THREAD

**Issue by TomoyoshiNakata** [kitalab/Tasks#39]
記事を作成・更新後、ブラウザの「戻る」ボタンを押して一覧画面に戻ると、それらの更新が反映されていない。ヘッダーの「←」を押したときは反映される。
一覧画面に戻ってからブラウザの「更新」ボタンを押すと反映される。

**Comment by kitatsuw** [comment]
「戻る」ボタンの仕様なので正常動作です。
