### ISSUE TITLE
絞り込みの条件に存在しない数値を入力しても一覧画面が表示される

### ISSUE THREAD

**Issue by TomoyoshiNakata** [kitalab/Tasks#40]
一覧画面で、絞り込み・ソート条件がアドレスバーに表示されるが（例:is_completion:1/user_id:1）、完了・未完了（is_completion）に「0」「1」「all」以外の値を入れた場合、またユーザーID（user_id）に存在しない値を入力した場合、選択肢が空白で表示される。
また、ソート条件に存在しない値を入力した場合、選択肢は「期限の近い順」が表示される。

**Comment by kitatsuw** [comment]
選択肢が空白は不具合、そのほかについてはDEFAULTの値が表示されるのが正常
